apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: yas-dev-strict-mtls
  namespace: yas-dev
spec:
  mtls:
    mode: STRICT
---
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: yas-dev-mtls
  namespace: yas-dev
spec:
  host: "*.yas-dev.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

