apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-inventory-from-selected-services
  namespace: yas-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: inventory
      app.kubernetes.io/name: inventory
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/yas-dev/sa/backoffice-bff
              - cluster.local/ns/yas-dev/sa/order
