apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-order-from-bff
  namespace: yas-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: order
      app.kubernetes.io/name: order
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - cluster.local/ns/yas-dev/sa/storefront-bff
              - cluster.local/ns/yas-dev/sa/backoffice-bff
