apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: yas-staging
  namespace: argocd
spec:
  description: YAS staging environment

  sourceRepos:
    - https://github.com/mrDanh11/yas_cd.git

  destinations:
    - namespace: yas-staging
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
