apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yas-staging-backoffice-ui
  namespace: argocd
spec:
  project: yas-staging

  source:
    repoURL: https://github.com/mrDanh11/yas_cd.git
    targetRevision: main
    path: k8s/charts/backoffice-ui
    helm:
      releaseName: backoffice-ui
      parameters:
        - name: ui.image.repository
          value: mrdanh/yas-backoffice-ui
        - name: ui.image.tag
          value: main
        - name: ui.image.pullPolicy
          value: Always
        - name: ui.ingress.className
          value: traefik
        - name: ui.resources.requests.memory
          value: 200Mi
        - name: ui.resources.requests.cpu
          value: 100m
        - name: ui.resources.limits.memory
          value: 350Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: yas-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
