apiVersion: v2
name: yas-service-mesh
description: Helm chart to configure Istio Service Mesh (mTLS, AuthorizationPolicies, and VirtualServices) for YAS microservices
type: application
version: 0.1.0
appVersion: "1.0.0"
